App UI
ignaciocervinoGlob/JavaBaseProject pull request #1
Opened 2021-09-16 16:09 UTC by ignaciocervinoGlob

## Description
First UI implemented for Parking System

## Story Type

- New feature ✅ 
- Change request
- Bug fix
- Tech

## How Can This Be Tested?

## Evidences
#### Main layout screenshot

![Screenshot_1631807612](https://user-images.githubusercontent.com/90403672/133646870-2a5aa4c4-69c5-48de-8407-8b315b9fd58e.png)

## Checklist

- All unit Test passed

## Tested on
Nexus 5

2021-09-16 16:19 UTC, SartiMau requested changes
please transform the jpg image into a webp one

2021-09-16 16:19 UTC, SartiMau commented on app/src/main/res/values-night/themes.xml
> +        <item name="android:windowBackground">@drawable/background_main</item>
for simplicity you can delete the values-night

2021-09-16 16:19 UTC, SartiMau commented on app/src/main/res/layout/activity_main.xml
>  </androidx.constraintlayout.widget.ConstraintLayout>
to avoid this error just add an empty line at the end of the file, please check all the files

2021-09-16 16:19 UTC, SartiMau commented on app/src/main/res/layout/activity_main.xml
> +        android:textColor="@color/white"
you can create a style for these properties :

- android:textColor
- android:textSize

2021-09-16 16:19 UTC, SartiMau commented on app/src/main/res/layout/activity_main.xml
> +        android:textColor="@color/white"
you can create a style for these properties :

android:textColor
android:textSize

2021-09-16 16:19 UTC, SartiMau commented on app/src/main/res/values/themes.xml
> +        <item name="android:windowBackground">@drawable/background_main</item>
a style with only one property does not make sense, please put this background in the layout of the xml

2021-09-16 17:40 UTC, nicolbidone commented
please review the id names using 
https://docs.google.com/presentation/d/1ruwOyqgrLEUkNbM7sEcuxLZ4IWDjzjX0OdytV6wUGCk/edit#slide=id.p25

2021-09-16 18:08 UTC, MarcosCGlobant commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintTop_toBottomOf="@+id/title_text" />
```suggestion
        app:layout_constraintTop_toBottomOf="@id/title_text" />
```

avoid using the "+" when referencing ids, because it makes a new reference of it and it will generate memory issues when searching for that id

2021-09-16 18:32 UTC, ignaciocervinoGlob commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintTop_toBottomOf="@+id/title_text" />
done

2021-09-16 18:36 UTC, MarcosCGlobant approved these changes
LGTM

2021-09-16 20:20 UTC, lucianoeli approved these changes

2021-09-17 12:53 UTC, nicolbidone approved these changes

2021-09-17 13:13 UTC, SartiMau approved these changes

2021-09-17 15:12 UTC, merged