Persist the number of parking available
ignaciocervinoGlob/JavaBaseProject pull request #3
Opened 2021-09-21 14:22 UTC by ignaciocervinoGlob

Added the functionality to persist the number of parking available using the button "Select Parking" that gets the input from the user and shows a toast with the value.

- New feature ✅ 

## Evidences
<img width="207" alt="parkingLots" src="https://user-images.githubusercontent.com/90403672/134188280-558a4533-7f40-4722-a682-edfeb16a349c.png">

![parkingLotsGif](https://user-images.githubusercontent.com/90403672/134188311-604325cb-ec88-44ea-ac60-b1ccb293021a.gif)

## Tested on
Pixel 2XL

2021-09-21 15:18 UTC, MarcosCGlobant commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintBottom_toTopOf="@+id/button_main_activity_select_parking"
```suggestion
        app:layout_constraintBottom_toTopOf="@id/button_main_activity_select_parking"
```
remember to avoid using the "+" on the IDs for the constraints definitions, it will make a new reference of the ID and generate memory issues when looking for that ID

2021-09-21 15:18 UTC, MarcosCGlobant commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintTop_toBottomOf="@+id/text_main_activity_title"
in here as well

2021-09-21 15:25 UTC, ignaciocervinoGlob commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintBottom_toTopOf="@+id/button_main_activity_select_parking"
oh i forgot about that, thanks! Done

2021-09-21 15:26 UTC, ignaciocervinoGlob commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintTop_toBottomOf="@+id/text_main_activity_title"
done

2021-09-21 15:34 UTC, MarcosCGlobant approved these changes
LGTM

2021-09-21 19:26 UTC, nicolbidone requested changes

2021-09-21 19:26 UTC, nicolbidone commented on app/src/main/java/com/mobile/tandil/javabaseproject/mvp/model/SelectParkingModel.java
> +        parkingLots = 0;
please set this value as a constant this is considered a harcode

2021-09-21 19:26 UTC, nicolbidone commented on app/src/main/java/com/mobile/tandil/javabaseproject/mvp/presenter/SelectParkingPresenter.java
> +        String lots = view.getParkingLots();
please avoid single-use variables

2021-09-21 19:26 UTC, nicolbidone commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintHorizontal_bias="0.491"
you can omit this attribute by default bias is 0.5

2021-09-21 19:26 UTC, nicolbidone commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintHorizontal_bias="0.495"
you can omit this attribute by default bias is 0.5

2021-09-21 19:26 UTC, nicolbidone commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintVertical_bias="0.504" />
you can omit this attribute by default bias is 0.5

2021-09-21 19:26 UTC, nicolbidone commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintHorizontal_bias="0.493"
you can omit this attribute by default bias is 0.5

2021-09-21 19:26 UTC, nicolbidone commented on app/src/main/res/drawable/parking_lot_input.xml
> +</selector>
which is the purpose of this selector?

2021-09-21 19:44 UTC, ignaciocervinoGlob commented on app/src/main/res/drawable/parking_lot_input.xml
> +</selector>
is the rectangle shape around the parking lots input

2021-09-21 20:00 UTC, ignaciocervinoGlob commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintHorizontal_bias="0.491"
done

2021-09-21 20:00 UTC, ignaciocervinoGlob commented on app/src/main/java/com/mobile/tandil/javabaseproject/mvp/presenter/SelectParkingPresenter.java
> +        String lots = view.getParkingLots();
done

2021-09-21 20:00 UTC, ignaciocervinoGlob commented on app/src/main/java/com/mobile/tandil/javabaseproject/mvp/model/SelectParkingModel.java
> +        parkingLots = 0;
done

2021-09-21 20:00 UTC, ignaciocervinoGlob commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintHorizontal_bias="0.495"
done

2021-09-21 20:00 UTC, ignaciocervinoGlob commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintVertical_bias="0.504" />
done

2021-09-21 20:00 UTC, ignaciocervinoGlob commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintHorizontal_bias="0.493"
done

2021-09-22 13:31 UTC, nicolbidone commented on app/src/main/res/layout/activity_main.xml
> +        android:inputType="number"
ems and inputType should be on the style also

2021-09-22 13:54 UTC, ignaciocervinoGlob commented on app/src/main/res/layout/activity_main.xml
> +        android:inputType="number"
done

2021-09-22 13:56 UTC, nicolbidone approved these changes

2021-09-22 13:57 UTC, BQuinteros approved these changes

2021-09-22 15:31 UTC, mauroLonghi approved these changes

2021-09-22 15:32 UTC, merged