New screen with the parking ticket UI and implementation
ignaciocervinoGlob/JavaBaseProject pull request #5
Opened 2021-09-30 19:55 UTC by ignaciocervinoGlob

## Description
Added a new screen for the user to fill and submit the parking reservation ticket (select the dates, enter the parking lot and security code). 

## Project structure
<img width="189" alt="projectStructure" src="https://user-images.githubusercontent.com/90403672/135515595-d0bbbff5-5473-41da-90cb-e227a8983d37.png">

## Evidences

https://user-images.githubusercontent.com/90403672/135521437-62b9a5ae-8248-41c7-9d4f-e9491b7a9cb7.mp4

## Tested on
Pixel 2XL

2021-09-30 20:09 UTC, BQuinteros approved these changes

2021-10-01 12:51 UTC, SartiMau requested changes

2021-10-01 12:51 UTC, SartiMau commented on app/src/main/java/com/mobile/tandil/javabaseproject/mvp/model/DateType.java
> +public enum DateType {
please move this to a utils package

2021-10-01 12:51 UTC, SartiMau commented on app/src/main/java/com/mobile/tandil/javabaseproject/mvp/model/ParkingReservationModel.java
> +        if (dateType == DateType.START)
please use curly braces in each statement

2021-10-01 12:51 UTC, SartiMau commented on app/src/main/java/com/mobile/tandil/javabaseproject/mvp/model/ParkingReservationModel.java
> +        if (dateType == DateType.START)
same

2021-10-01 12:51 UTC, SartiMau commented on app/src/main/java/com/mobile/tandil/javabaseproject/mvp/presenter/ParkingReservationPresenter.java
> +        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm", Locale.US);
please put the format style in a constantUtils class

2021-10-01 12:51 UTC, SartiMau commented on app/src/main/java/com/mobile/tandil/javabaseproject/mvp/presenter/ParkingReservationPresenter.java
> +        if (model.getDateType() == DateType.START)
add the curly braces

2021-10-01 12:51 UTC, SartiMau commented on app/src/main/java/com/mobile/tandil/javabaseproject/mvp/presenter/ParkingReservationPresenter.java
> +        if (model.getDateType() == DateType.START)
add the curly braces

2021-10-01 12:51 UTC, SartiMau commented on app/src/main/java/com/mobile/tandil/javabaseproject/mvp/view/ParkingReservationView.java
> +            thisActivity.startActivity(new Intent(getActivity(), MainActivity.class));
instead of getActivity() please use the variable thisActivity

2021-10-01 12:51 UTC, SartiMau commented on app/src/main/res/values/styles.xml
> +    <style name="NewParkingReservationActivityStyle">
an style with only one property does not make sense, please remove it and use property

2021-10-01 12:51 UTC, SartiMau commented on app/src/main/res/values/styles.xml
> +    <style name="ButtonActivityNewParkingReservationCancel" parent="ButtonSetParkingLotsDialogCancelStyle">
same, and the style below

2021-10-01 12:51 UTC, SartiMau commented on app/src/main/res/values/styles.xml
> +    <style name="ButtonActivityNewParkingEndDate" parent="ButtonActivityNewParkingStartDate">
please remove this empty style

2021-10-01 12:51 UTC, SartiMau commented on app/src/main/res/values/styles.xml
> +    <style name="TextActivityNewParkingEndDateLabel" parent="TextActivityNewParkingStartDateLabel">
same

2021-10-01 12:51 UTC, SartiMau commented on app/src/main/res/values/styles.xml
> +    <style name="ParkingReservationActivityInputParkingLotNumber">
same

2021-10-01 12:51 UTC, SartiMau commented on app/src/main/res/values/styles.xml
> +    <style name="ParkingReservationActivityInputSecurityCodeNumber">
same

2021-10-01 13:31 UTC, ignaciocervinoGlob commented on app/src/main/java/com/mobile/tandil/javabaseproject/mvp/view/ParkingReservationView.java
> +            thisActivity.startActivity(new Intent(getActivity(), MainActivity.class));
done

2021-10-01 13:33 UTC, ignaciocervinoGlob commented on app/src/main/java/com/mobile/tandil/javabaseproject/mvp/presenter/ParkingReservationPresenter.java
> +        if (model.getDateType() == DateType.START)
done

2021-10-01 13:33 UTC, ignaciocervinoGlob commented on app/src/main/java/com/mobile/tandil/javabaseproject/mvp/presenter/ParkingReservationPresenter.java
> +        if (model.getDateType() == DateType.START)
done

2021-10-01 13:35 UTC, ignaciocervinoGlob commented on app/src/main/java/com/mobile/tandil/javabaseproject/mvp/presenter/ParkingReservationPresenter.java
> +        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm", Locale.US);
done

2021-10-01 13:36 UTC, ignaciocervinoGlob commented on app/src/main/java/com/mobile/tandil/javabaseproject/mvp/model/ParkingReservationModel.java
> +        if (dateType == DateType.START)
done both

2021-10-01 13:40 UTC, ignaciocervinoGlob commented on app/src/main/java/com/mobile/tandil/javabaseproject/mvp/model/DateType.java
> +public enum DateType {
done

2021-10-01 14:07 UTC, SartiMau requested changes

2021-10-01 14:07 UTC, SartiMau commented on app/src/main/java/com/mobile/tandil/javabaseproject/utils/ConstantUtils.java
> +    public static SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm", Locale.US);
I was talking about putting here only the format string 

"dd/MM/yyyy HH:mm"

2021-10-01 14:14 UTC, ignaciocervinoGlob commented on app/src/main/java/com/mobile/tandil/javabaseproject/utils/ConstantUtils.java
> +    public static SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm", Locale.US);
done

2021-10-01 14:19 UTC, SartiMau approved these changes

2021-10-01 14:28 UTC, merged