Saving reservations in a third-level cache using a Mutable Map
ignaciocervinoGlob/JavaBaseProject pull request #7
Opened 2021-10-18 14:31 UTC by ignaciocervinoGlob

## Description
Saving all new reservations in an object in memory using a MutableMap. Integrating the new Kotlin files with the old Java ones.

## Evidences
<img width="282" alt="pr7" src="https://user-images.githubusercontent.com/90403672/137751044-bd98fe79-14cb-49c7-a479-d152724c842e.png">

2021-10-18 15:43 UTC, nicolbidone commented on app/src/main/java/com/mobile/tandil/javabaseproject/data/database/ParkingSystemDatabase.kt
> +    @JvmStatic
do you need this anotation?

2021-10-18 15:43 UTC, nicolbidone commented on app/src/main/java/com/mobile/tandil/javabaseproject/data/database/ParkingSystemDatabase.kt
> +        val lot = newReservation.parkingLot
here you can use with instead of create a var

2021-10-18 15:43 UTC, nicolbidone commented on app/src/main/java/com/mobile/tandil/javabaseproject/data/entity/ParkingReservation.kt
> +import java.util.*
please avoid wildcard imports

2021-10-18 15:43 UTC, nicolbidone commented on settings.gradle
> -}
why do you remove this?

2021-10-18 15:43 UTC, nicolbidone commented on app/src/main/java/com/mobile/tandil/javabaseproject/data/database/ParkingSystemDatabase.kt
> +            reservations[lot] = newParkingReservationList
you can simplify this in a single line using listOf()

2021-10-18 15:43 UTC, nicolbidone commented on app/src/main/java/com/mobile/tandil/javabaseproject/data/database/ParkingSystemDatabase.kt
> +    fun getReservations() = reservations
here you should return an inmutable map

2021-10-18 15:43 UTC, nicolbidone commented on app/src/main/java/com/mobile/tandil/javabaseproject/mvp/model/ParkingReservationModel.kt
> +import java.util.*
please avoid wildcard imports

2021-10-18 16:16 UTC, ignaciocervinoGlob commented on settings.gradle
> -}
I was having some issues with Kotlin setup and I figure it out with a stack overflow solution about the gradle files

2021-10-18 16:16 UTC, ignaciocervinoGlob commented on app/src/main/java/com/mobile/tandil/javabaseproject/data/database/ParkingSystemDatabase.kt
> +            reservations[lot] = newParkingReservationList
done

2021-10-18 16:16 UTC, ignaciocervinoGlob commented on app/src/main/java/com/mobile/tandil/javabaseproject/data/database/ParkingSystemDatabase.kt
> +    fun getReservations() = reservations
done

2021-10-18 16:17 UTC, ignaciocervinoGlob commented on app/src/main/java/com/mobile/tandil/javabaseproject/mvp/model/ParkingReservationModel.kt
> +import java.util.*
done

2021-10-18 16:17 UTC, ignaciocervinoGlob commented on app/src/main/java/com/mobile/tandil/javabaseproject/data/entity/ParkingReservation.kt
> +import java.util.*
done

2021-10-18 16:17 UTC, ignaciocervinoGlob commented on app/src/main/java/com/mobile/tandil/javabaseproject/data/database/ParkingSystemDatabase.kt
> +        val lot = newReservation.parkingLot
done

2021-10-18 16:17 UTC, ignaciocervinoGlob commented on app/src/main/java/com/mobile/tandil/javabaseproject/data/database/ParkingSystemDatabase.kt
> +    @JvmStatic
done

2021-10-18 16:58 UTC, mauroLonghi approved these changes

2021-10-19 13:07 UTC, vsmartinez requested changes
if you like you can implement my observation, the resulting code will be more isolated between classes and the activity will be cleaner.

2021-10-19 13:07 UTC, vsmartinez commented on app/src/main/java/com/mobile/tandil/javabaseproject/activity/MainActivity.java
>          binding = ActivityMainBinding.inflate(getLayoutInflater());
Line 20 and 21 can be moved inside of `SelectParkingView` class, doing this you will be able to remove `ParkingLotsInputlistener` interface.

Then `setLlisteners` method functionality can be moved inside `SelectParkingView`  class.

2021-10-19 13:07 UTC, vsmartinez commented on app/src/main/java/com/mobile/tandil/javabaseproject/activity/MainActivity.java
>          binding = ActivityMainBinding.inflate(getLayoutInflater());
Remove `shareLotsInput`. The view should provide callbacks

2021-10-20 18:51 UTC, ignaciocervinoGlob commented on app/src/main/java/com/mobile/tandil/javabaseproject/activity/MainActivity.java
>          binding = ActivityMainBinding.inflate(getLayoutInflater());
I think I got the concept, now the code is much cleaner  and understandable.
Thanks for this suggestion :)

2021-10-20 21:27 UTC, vsmartinez requested changes

2021-10-20 21:27 UTC, vsmartinez commented on app/src/main/java/com/mobile/tandil/javabaseproject/activity/ParkingReservationActivity.kt
> +    override fun onDateSet(datePicker: DatePicker, year: Int, monthOfYear: Int, dayOfMonth: Int) {
What about this one? 
Could be pushed inside of the view like you did with the others (good job btw)

2021-10-21 14:24 UTC, nicolbidone commented on app/src/test/java/com/mobile/tandil/javabaseproject/mvp/presenter/MainPresenterTest.java
> +        //model = new MainModel();
please remove commented lines

2021-10-21 14:24 UTC, nicolbidone commented on app/src/main/java/com/mobile/tandil/javabaseproject/mvp/view/SetParkingLotsView.kt
> +    }
instead of return here you can use =

2021-10-21 14:24 UTC, nicolbidone commented on app/src/main/java/com/mobile/tandil/javabaseproject/mvp/view/SetParkingLotsView.kt
> +        dialogFragment?.dismiss()
there's no need to create an extra val here

2021-10-21 14:24 UTC, nicolbidone commented on app/src/main/java/com/mobile/tandil/javabaseproject/mvp/view/ParkingReservationView.kt
> +        GeneralUtils.showToast(context, context!!.getString(R.string.parking_reservation_activity_success_toast))
please avoid using !! instead use context?.let{ ... }

2021-10-21 14:24 UTC, nicolbidone commented on app/src/main/java/com/mobile/tandil/javabaseproject/mvp/view/ParkingReservationView.kt
> +        GeneralUtils.showToast(context, context!!.getString(R.string.parking_reservation_activity_error_toast_empty_input))
please avoid using !! instead use context?.let{ ... }

2021-10-21 14:24 UTC, nicolbidone commented on app/src/main/java/com/mobile/tandil/javabaseproject/mvp/view/ParkingReservationView.kt
> +        return binding.inputSecurityCodeReservationActivity.editText!!.text.toString()
please avoid using !! instead use editText?.let{ ... }

2021-10-21 14:24 UTC, nicolbidone commented on app/src/main/java/com/mobile/tandil/javabaseproject/mvp/view/ParkingReservationView.kt
> +        return binding.inputParkingLotReservationActivity.editText!!.text.toString()
please avoid using !! instead use editText?.let{ ... }

2021-10-21 14:24 UTC, nicolbidone commented on app/src/main/java/com/mobile/tandil/javabaseproject/mvp/view/ParkingReservationView.kt
> +        return binding.inputSecurityCodeReservationActivity.editText!!.text.toString()
instead of return here you can use =

2021-10-21 14:24 UTC, nicolbidone commented on app/src/main/java/com/mobile/tandil/javabaseproject/mvp/view/ParkingReservationView.kt
> +        return binding.inputParkingLotReservationActivity.editText!!.text.toString()
instead of return here you can use =

2021-10-21 14:24 UTC, nicolbidone commented on app/src/main/java/com/mobile/tandil/javabaseproject/mvp/view/ParkingReservationView.kt
> +            activity!!,
please avoid using !! instead use activity?.let{ ... }

2021-10-21 14:24 UTC, nicolbidone commented on app/src/main/java/com/mobile/tandil/javabaseproject/mvp/view/ParkingReservationView.kt
> +        timePickerDialog.show()
please avoid using a nullable cast instead use activity?.let{ ... }

2021-10-21 14:24 UTC, nicolbidone commented on app/src/main/java/com/mobile/tandil/javabaseproject/mvp/view/ParkingReservationView.kt
> +            activity as OnDateSetListener?,
please avoid using a nullable cast instead use activity?.let{ ... }

2021-10-21 14:24 UTC, nicolbidone commented on app/src/main/java/com/mobile/tandil/javabaseproject/mvp/view/ParkingReservationView.kt
> +        datePickerDialog.show()
here you can use apply to avoid the datePickerDialog val

2021-10-21 16:57 UTC, ignaciocervinoGlob commented on app/src/main/java/com/mobile/tandil/javabaseproject/mvp/view/ParkingReservationView.kt
> +        datePickerDialog.show()
done

2021-10-21 16:57 UTC, ignaciocervinoGlob commented on app/src/main/java/com/mobile/tandil/javabaseproject/mvp/view/ParkingReservationView.kt
> +            activity as OnDateSetListener?,
done

2021-10-21 16:57 UTC, ignaciocervinoGlob commented on app/src/main/java/com/mobile/tandil/javabaseproject/mvp/view/ParkingReservationView.kt
> +        timePickerDialog.show()
done

2021-10-21 16:57 UTC, ignaciocervinoGlob commented on app/src/main/java/com/mobile/tandil/javabaseproject/mvp/view/ParkingReservationView.kt
> +            activity!!,
done

2021-10-21 16:57 UTC, ignaciocervinoGlob commented on app/src/main/java/com/mobile/tandil/javabaseproject/mvp/view/ParkingReservationView.kt
> +        return binding.inputParkingLotReservationActivity.editText!!.text.toString()
done

2021-10-21 16:57 UTC, ignaciocervinoGlob commented on app/src/main/java/com/mobile/tandil/javabaseproject/mvp/view/ParkingReservationView.kt
> +        return binding.inputSecurityCodeReservationActivity.editText!!.text.toString()
done

2021-10-21 16:57 UTC, ignaciocervinoGlob commented on app/src/main/java/com/mobile/tandil/javabaseproject/mvp/view/ParkingReservationView.kt
> +        GeneralUtils.showToast(context, context!!.getString(R.string.parking_reservation_activity_error_toast_empty_input))
done

2021-10-21 16:57 UTC, ignaciocervinoGlob commented on app/src/main/java/com/mobile/tandil/javabaseproject/mvp/view/ParkingReservationView.kt
> +        GeneralUtils.showToast(context, context!!.getString(R.string.parking_reservation_activity_success_toast))
done

2021-10-21 16:57 UTC, ignaciocervinoGlob commented on app/src/main/java/com/mobile/tandil/javabaseproject/mvp/view/SetParkingLotsView.kt
> +        dialogFragment?.dismiss()
done

2021-10-21 16:57 UTC, ignaciocervinoGlob commented on app/src/main/java/com/mobile/tandil/javabaseproject/mvp/view/SetParkingLotsView.kt
> +    }
done

2021-10-21 16:57 UTC, ignaciocervinoGlob commented on app/src/test/java/com/mobile/tandil/javabaseproject/mvp/presenter/MainPresenterTest.java
> +        //model = new MainModel();
done

2021-10-22 17:21 UTC, ignaciocervinoGlob commented on app/src/main/java/com/mobile/tandil/javabaseproject/activity/ParkingReservationActivity.kt
> +    override fun onDateSet(datePicker: DatePicker, year: Int, monthOfYear: Int, dayOfMonth: Int) {
I was thinking about that one since it's a bit different from the others, but finally I figure out how to push it inside the view.
Thanks for pointing it out!

2021-10-22 17:40 UTC, nicolbidone commented on app/build.gradle
> +        minSdk 24
please do not update minSdk

2021-10-22 18:17 UTC, ignaciocervinoGlob commented on app/build.gradle
> +        minSdk 24
done

2021-10-22 19:13 UTC, BQuinteros approved these changes

2021-10-22 19:47 UTC, SartiMau commented on app/src/main/java/com/mobile/tandil/javabaseproject/utils/ConstantUtils.kt
> +    const val EMPTY_STRING = " "
be careful because this is not an empty string this is a white space. If you do EMPTY_STRING.isEmpty() will response false.

This should be 
`    const val EMPTY_STRING = ""`

2021-10-22 19:50 UTC, ignaciocervinoGlob commented on app/src/main/java/com/mobile/tandil/javabaseproject/utils/ConstantUtils.kt
> +    const val EMPTY_STRING = " "
done

2021-10-22 20:30 UTC, SartiMau approved these changes

2021-10-22 20:37 UTC, vsmartinez approved these changes
LGTM

2021-10-22 20:41 UTC, nicolbidone approved these changes

2021-10-25 12:09 UTC, merged